# Generated by Django 4.2.4 on 2023-12-13 19:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_post_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='UserPost',
        ),
    ]
