# Generated by Django 4.2.4 on 2023-12-13 22:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_userpost_parent_alter_userpost_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPost',
            new_name='Post',
        ),
    ]
