# Generated by Django 4.2.7 on 2023-12-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_rename_userpost_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
